# Bigger on-screen UI
osd-font-size=36
osd-bar-h=3
osd-border-size=2

# Bigger subtitles
sub-font-size=44

# Wayland-friendly video output
gpu-context=wayland
vo=gpu-next

# Native size for small videos, shrink only large ones
autofit-larger=80%x80%
geometry=50%:50%

save-position-on-quit=yes
keep-open=yes
