# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# Hypridle 
# Original config submitted by https://github.com/SherLock707                                                       
                                                      
$iDIR="dialog-information-symbolic"

general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called) 
    # unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ on = true })" # make sure the screen is back on after sleep (not strictly necessary, but just in case)
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

# Turn off screen quickly if session is already locked
listener {
    timeout = 10
    on-timeout = pidof hyprlock && hyprctl dispatch "hl.dsp.dpms({ on = false })"
    on-resume = pidof hyprlock && hyprctl dispatch "hl.dsp.dpms({ on = true })"
}

# Suspend after 1 min if session is already locked
listener {
    timeout = 60
    on-timeout = pidof hyprlock && systemctl suspend
}

# Warn
# listener {
#     timeout = 540                     # 9 min
#     on-timeout = notify-send -i $iDIR "Idle" # command to run when timeout has passed
#     on-resume = notify-send -i $iDIR "Exit idle" # command to run when activity is detected after timeout has fired.
# }

# Screenlock
listener {
    timeout = 600                     # 10 min
    on-timeout = loginctl lock-session # command to run when timeout has passed
    #on-resume = notify-send -i $iDIR " System Unlocked!"  # command to run when activity is detected after timeout has fired.
}

# Turn off screen 
listener {
    timeout = 630                            # 10.5 min
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ on = false })"  # command to run when timeout has passed
    on-resume = hyprctl dispatch "hl.dsp.dpms({ on = true })"    # command to run when activity is detected after timeout has fired.
}

# Suspend
listener {
   timeout = 660                            # 11 min
   on-timeout = systemctl suspend # command to run when timeout has passed
    # on-resume = notify-send -i $iDIR " Oh! you're back" "Hello !!!"  # command to run when activity is detected after timeout has fired.
}
