$Scripts = $HOME/.config/hypr/scripts

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = $HOME/.config/rofi/.current_wallpaper
    color = rgb(0,0,0)
    blur_size = 4
    blur_passes = 3
    noise = 0.01
    contrast = 1.0
    brightness = 0.6
    vibrancy = 0.1
    vibrancy_darkness = 0.0
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.9)
    font_size = 62
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -190
    halign = center
    valign = top
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A, %-d %B')"
    color = rgba(255, 255, 255, 0.5)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -300
    halign = center
    valign = top
}

# USER
# label {
#     monitor =
#     text = $USER
#     color = rgba(255, 255, 255, 0.4)
#     font_size = 16
#     font_family = JetBrainsMono Nerd Font
#     position = 0, 5
#     halign = center
#     valign = center
# }

# INPUT FIELD
input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(255, 255, 255, 0.15)
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(255, 255, 255, 0.8)

    # Monokai cyan while checking password
    check_color = rgba(102, 217, 239, 0.8)

    # Monokai red/pink on wrong password
    fail_color = rgba(249, 38, 114, 0.9)
    fail_text = <span foreground="##F92672">Wrong password</span>

    capslock_color = rgb(F92672)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span foreground="##ffffff55" font="JetBrainsMono Nerd Font Light 14">Password</span>
    hide_input = false
    rounding = 12
    position = 0, -10
    halign = center
    valign = center
}

# Uptime
label {
    monitor =
    text = cmd[update:60000] echo "$(uptime -p)"
    color = rgba(255, 255, 255, 0.3)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = -20, 40
    halign = right
    valign = bottom
}

# Battery
label {
    monitor =
    text = cmd[update:1000] echo "$($Scripts/Battery.sh)"
    color = rgba(255, 255, 255, 0.3)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = -20, 15
    halign = right
    valign = bottom
}
